config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    
    get 'new_phone', to: 'users/registrations#new_phone'
    post 'create_user', to: 'users/registrations#create_user'
    post 'create_phone', to: 'users/registrations#create_phone'
    post 'create_address', to: 'users/registrations#create_address'
    get 'new_card', to: 'users/registrations#new_card'
    post 'save_user', to: 'users/registrations#save_user'
  end
  root "items#index"
  resources :items, only: [:index, :show, :edit, :update, :destroy] do
    collection do 
      get 'new'
      post 'create'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      post 'pay'
    end
  end
  resources :mypages, only: [:show, :edit,] do
    member do
      get 'on_sale'
      get 'logout'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      get 'done'
    end
  end
  resources :cards, only: [:show, :new, :create] 
  resources :addresses, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_aside.html.haml
.aside
  .aside__main
    .aside__main__left
      %h1 スマホでかんたんフリマアプリ
      %h2 今すぐ無料ダウンロード！
      .aside__main__left__api
        = link_to root_path, class: ‘logo-red’ do
          = image_tag ‘logo_red.svg’
        = link_to root_path, class: ‘logo-app’ do
          = image_tag ‘logo_white.svg’
        = link_to root_path, class: ‘logo-google’ do
          = image_tag ‘logo_white.svg’
    .aside__main__right
      = image_tag ‘image-bgi2.jpg’, class: ‘image-bgi2

app/views/shared/_breadcrumbs.html.haml
.breadcrumbs
  .content-bread
  = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/shared/_camera.html.haml
.ii-camera
  - if user_signed_in?
    = link_to items_path, class: "ii-camera__btn" do
      .ii-camera__btn__box
        .ii-camera__btn__box--text 出品
        = icon('fas', 'camera')
  - else 
    = link_to new_user_registration_path, class: "ii-camera__btn" do
      .ii-camera__btn__box
        .ii-camera__btn__box--text 出品
        = icon('fas', 'camera')

app/views/shared/_contents.html.haml
.contents

app/views/shared/_footer1.html.haml
.aside
  .aside__main
    .aside__main__left
      %h1 スマホでかんたんフリマアプリ
      %h2 今すぐ無料ダウンロード！
      .aside__main__left__api
        = link_to root_path, class: 'logo-red' do
          = image_tag 'logo_red.svg'
        = link_to root_path do
          = image_tag 'app-store.png', class: 'logo-app'
        = link_to root_path do
          = image_tag 'google-play.png', class: 'logo-google'
    .aside__main__right
      = image_tag 'image-bgi2.jpg', class: 'image-bgi2'


.footer1
  .footer1__box
    .footer1__box__info
      %h1 フリマ66dについて
      %ul.footer1__box__info__link
        %li.footer1__box__info__link__list
          = link_to root_path, class: "footer-link"  do
            会社概要（運営会社）
        %li.footer1__box__info__link__list
          = link_to root_path, class: "footer-link"  do
            採用情報
        %li.footer1__box__info__link__list
          = link_to root_path, class: "footer-link"  do
            プレスリリース
        %li.footer1__box__info__link__list
          = link_to root_path, class: "footer-link"  do
            公式ブログ
        %li.footer1__box__info__link__list
          = link_to root_path, class: "footer-link"  do
            フリマ66dロゴ利用ガイドライン
        %li.footer1__box__info__link__list
          = icon 'fab', 'facebook', class: 'fo1-icon'
          = icon 'fab', 'twitter', class: 'fo1-icon'
    .footer1__box__guide
      %h2 ヘルプ&ガイド
      %ul.footer1__box__guide__link
        %li.footer1__box__guide__link__list
          = link_to root_path, class: "footer-link"  do
            フリマ66dガイド
        %li.footer1__box__guide__link__list
          = link_to root_path, class: "footer-link"  do
            らくらくフリマ66d便
        %li.footer1__box__guide__link__list
          = link_to root_path, class: "footer-link"  do
            ゆうゆうフリマ66d便
        %li.footer1__box__guide__link__list
          = link_to root_path, class: "footer-link"  do
            大型フリマ66d便
        %li.footer1__box__guide__link__list
          = link_to root_path, class: "footer-link"  do
            車体取引ガイド
        %li.footer1__box__guide__link__list
          = link_to root_path, class: "footer-link"  do
            フリマ66dあんしん・あんぜん宣言！
        %li.footer1__box__guide__link__list
          = link_to root_path, class: "footer-link"  do
            偽ブランド品撲滅への取り組み
        %li.footer1__box__guide__link__list
          = link_to root_path, class: "footer-link"  do
            フリマ66dボックス
    .footer1__box__service
      %h3 プライバシーと利用規約
      %ul.footer1__box__service__link1
        %li.footer1__box__service__link1__list
          = link_to root_path, class: "footer-link"  do
            プライバシーポリシー
        %li.footer1__box__service__link1__list
          = link_to root_path, class: "footer-link"  do
            フリマ66d利用規約
        %li.footer1__box__service__link1__list
          = link_to root_path, class: "footer-link"  do
            あんしんスマホサポート制度に関する利用特約
        %li.footer1__box__service__link1__list
          = link_to root_path, class: "footer-link"  do
            コンプライアンスポリシー
      %ul.footer1__box__service__linkguide
        %li.footer1__box__service__link2__list
          = link_to root_path, class: "footer-link"  do
            個人データの安全管理に係る基本方針
        %li.footer1__box__service__link2__list
          = link_to root_path, class: "footer-link"  do
            特定商取引に関する表記
        %li.footer1__box__service__link2__list
          = link_to root_path, class: "footer-link"  do
            資金決済法に基づく表示
        %li.footer1__box__service__link2__list
          = link_to root_path, class: "footer-link"  do
            法令順守と犯罪抑止のために
    .footer1__box__country
      %h4 国
      %ul.footer1__box__country__link
        %li.footer1__box__country__link__list
          = link_to root_path, class: "footer-link"  do
            日本
        %li.footer1__box__country__link__list
          = link_to root_path, class: "footer-link"  do
            United States
  .footer1__bottom
    .footer1__bottom__logo
      = link_to root_path do
        = image_tag 'logo_white.svg', class: 'fremalogo-footer'
    .footer1__bottom__copyright
      %small @Frema,lnc.

app/views/shared/_footer2.html.haml
%footer.footer2
  %nav.f2-nav
    %ul.f2-clearfix
      %li.f2-text
        = link_to "プライバシーポリシー",root_path, class:"f2-link"
      %li.f2-text
        = link_to "フリーマーケット利用規約",root_path, class:"f2-link"
      %li.f2-text
        = link_to "特定商取引に関する表記",root_path, class:"f2-link"
        
  =link_to root_path, class: "footer2_logo" do
    = image_tag 'logo_gray.svg', class:"f2-image"
  %p.f2-p
    %small.f-sall © 2020 freemarket

app/views/shared/_header1.html.haml
.header1
  .header1-main
    .header1-main__text
      .header1-main__text__logo
        = link_to root_path, class: 'fremalogo' do
          = image_tag 'fmarket_logo_red.svg'
      .header1-main__text__form

        = form_tag(search_items_path,:method => 'get') do
          = text_field_tag :keyword, '', class:'search-form', placeholder: "何かお探しですか？"
          = button_tag type: 'submit', :name => nil, class: 'search-icon' do
            = icon 'fas', 'search'

    .header1-main__nav
      .header1-main__nav__js
        .header1-main__nav__js__links
          = link_to root_path, class: "header1-main__nav__js__links__link"  do
            = icon 'fas', 'list', class: 'navicon'
            カテゴリーから探す
        .header1-main__nav__js__links
          = link_to root_path, class: "header1-main__nav__js__links__link"  do
            = icon 'fas', 'tag', class: 'navicon'
            ブランドから探す




      - if user_signed_in?      
        %ul.header1-main__nav__menu
          %li.header1-main__nav__menu__link
            = link_to root_path, class: "header1-main__nav__menu__link--mypage"  do
              = icon 'far', 'heart', class: 'menuicon'
              いいね！一覧
          %li.header1-main__nav__menu__link
            = link_to root_path, class: "header1-main__nav__menu__link--mypage"  do
              = icon 'far', 'bell', class: 'menuicon'
              お知らせ
          %li.header1-main__nav__menu__link
            = link_to root_path, class: "header1-main__nav__menu__link--mypage"  do
              = icon 'fas', 'check', class: 'menuicon'
              やることリスト
          %li.header1-main__nav__menu__link
            = link_to mypage_path(current_user.id), class: "header1-main__nav__menu__link--mypage"  do
              = icon 'far', 'user', class: 'menuicon'
              マイページ
      - else
        %ul.header1-main__nav__menu__member
          %li= link_to "新規会員登録", new_user_registration_path, class: 'header1-main__nav__menu__member__register'
          .color-change
            %li= link_to "ログイン", new_user_session_path, class: 'header1-main__nav__menu__member__login'

app/views/shared/_header2.html.haml
%header.header2
  =link_to root_path do
    = image_tag 'fmarket_logo_red.svg', class:"h2-image"

app/views/shared/_main.html.haml
%main.main

app/views/shared/_side-bar.html.haml
.side-bar
  %nav.my-page
    %ul.may-page__list
      %li.my-page__list__contents
        = link_to mypage_path(current_user.id), class: "my-page__list__contents--link" do
          マイページ
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          お知らせ
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          やることリスト
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          いいね！一覧
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to items_path, class: "my-page__list__contents--link" do
          出品する
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to on_sale_mypage_path(current_user.id), class: "my-page__list__contents--link" do
          出品した商品 - 出品中
          .my-page__list__contents--link--icon
            = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          出品した商品 - 取引中
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          出品した商品 - 売却済み
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          購入した商品 - 取引中
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          購入した商品 - 過去の取引
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          ニュース一覧
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          評価一覧
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          ガイド
          = icon('fas', 'chevron-right')
      %li.my-page__list__contents
        = link_to "#", class: "my-page__list__contents--link" do
          お問い合わせ
          = icon('fas', 'chevron-right')
  %nav.merupay
    %h.merupay__title メルペイ
    %ul.merupay__list
      %li.merupay__list__contents
        = link_to "#", class: "merupay__list__contents--link" do
          売上・振込申請
          = icon('fas', 'chevron-right')
      %li.merupay__list__contents
        = link_to "#", class: "merupay__list__contents--link" do
          ポイント
          = icon('fas', 'chevron-right')
  %nav.config
    %h.cinfig__title 設定
    %ul.config__list
      %li.config__list__contents
        = link_to edit_mypage_path(current_user.id), class: "config__list__contents--link" do
          プロフィール
          = icon('fas', 'chevron-right')
      %li.config__list__contents
        = link_to "#", class: "config__list__contents--link" do
          発送元・お届け先住所変更
          = icon('fas', 'chevron-right')
      %li.config__list__contents
      
        = link_to card_path(current_user.id), class: "config__list__contents--link" do
          支払い方法
          = icon('fas', 'chevron-right')
      %li.config__list__contents
        = link_to "#", class: "config__list__contents--link" do
          メール/パスワード
          = icon('fas', 'chevron-right')
      %li.config__list__contents
        = link_to address_path(current_user.id), class: "config__list__contents--link" do
          本人情報
          = icon('fas', 'chevron-right')
      %li.config__list__contents
        = link_to "#", class: "config__list__contents--link" do
          電話番号の確認
          = icon('fas', 'chevron-right')
      %li.config__list__contents
        = link_to logout_mypage_path(current_user.id), class: "config__list__contents--link" do
          ログアウト
          = icon('fas', 'chevron-right')