config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    
    get 'new_phone', to: 'users/registrations#new_phone'
    post 'create_user', to: 'users/registrations#create_user'
    post 'create_phone', to: 'users/registrations#create_phone'
    post 'create_address', to: 'users/registrations#create_address'
    get 'new_card', to: 'users/registrations#new_card'
    post 'save_user', to: 'users/registrations#save_user'
  end
  root "items#index"
  resources :items, only: [:index, :show, :edit, :update, :destroy] do
    collection do 
      get 'new'
      post 'create'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      post 'pay'
    end
  end
  resources :mypages, only: [:show, :edit,] do
    member do
      get 'on_sale'
      get 'logout'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      get 'done'
    end
  end
  resources :cards, only: [:show, :new, :create] 
  resources :addresses, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  
  def index
    @item = Item.find(params[:item_id])
  end

  def done
  end
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/purchase/done.html.haml
= render "shared/header2"

.contents
  .pd-contents
    .pd-contents__head
      取引完了
    .pd-contents__innner
      .pd-contents__innner__label
        .pd-contents__innner__label__sub
          商品到着までお待ちください
      .pd-contents__innner__add-text
        .pd-contents__innner__add-text__single              
        .pd-contents__innner__add-text__single
          .pd-contents__innner__add-text__single__box
            .pd-contents__innner__add-text__single__box__cn-btn-red
              = link_to "商品一覧に戻る", root_path, class: "cn-btn"
                
= render "shared/footer2" 

app/views/purchase/index.html.haml
= render "shared/header2"

.pi-main
  .pi-main__container
    .pi-main__container__head
      購入内容の確認
    .pi-main__container__item
      .pi-main__container__item__box
        .pi-main__container__item__box__in
          .pi-main__container__item__box__in__image
            = image_tag @item.images[0].source.url,width: "100%",height: "100%"
          .pi-main__container__item__box__in__detail
            .pi-main__container__item__box__in__detail__name
              = @item.name            
            .pi-main__container__item__box__in__detail__money
              .pi-main__container__item__box__in__detail__money__span
                = @item.price
              .pi-main__container__item__box__in__detail__money__fee
                （税込）送料込み


    .pi-main__container__form
      .pi-main__container__form__inner
        .pi-main__container__form__inner__price
          支払い金額
        .pi-main__container__form__inner__yen
          = @item.price
      .pi-main__container__form__point
        .pi-main__container__form__point__icon
          ■
        %label.pi-main__container__point__label
          ポイントを使用 (所持ポイント: P0)

      .pi-main__container__form__pay-form
        .pi-main__container__form__pay-form__inner
          .pi-main__container__form__pay-form__inner__text
            支払い方法
          .pi-main__container__form__pay-form__inner__pay
            .pi-main__container__form__pay-form__inner__pay__icon
              ⊕
            .pi-main__container__form__pay-form__inner__pay__text
              登録してください
      
      .pi-main__container__form__address
        .pi-main__container__form__address__inner
          .pi-main__container__form__address__inner__head
            .pi-main__container__form__address__inner__head__left
              配送先
            .pi-main__container__form__address__inner__head__right
              変更する
          .pi-main__container__form__address__inner__text
            .pi-main__container__form__address__inner__text__detail
              = current_user.address.postal_code
            .pi-main__container__form__address__inner__text__detail__h1
              = current_user.address.prefecture + current_user.address.municipality
            .pi-main__container__form__address__inner__text__detail__h2
              = current_user.nickname

      .pi-main__container__form__section
        - if current_user.card.present?
          = link_to "購入する", pay_item_path(@item.id), method: :post, class: 'pi-main__container__form__section__button', disabled: "disabled", type: "submit" 
        - else
          = link_to "クレジットカードを登録する", "cards/new", method: :get, class: 'pi-main__container__form__section__button', disabled: "disabled", type: "submit"    
        
        



= render "shared/footer2"     