config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    
    get 'new_phone', to: 'users/registrations#new_phone'
    post 'create_user', to: 'users/registrations#create_user'
    post 'create_phone', to: 'users/registrations#create_phone'
    post 'create_address', to: 'users/registrations#create_address'
    get 'new_card', to: 'users/registrations#new_card'
    post 'save_user', to: 'users/registrations#save_user'
  end
  root "items#index"
  resources :items, only: [:index, :show, :edit, :update, :destroy] do
    collection do 
      get 'new'
      post 'create'
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      post 'pay'
    end
  end
  resources :mypages, only: [:show, :edit,] do
    member do
      get 'on_sale'
      get 'logout'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      get 'done'
    end
  end
  resources :cards, only: [:show, :new, :create] 
  resources :addresses, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :saler, class_name: "User"
  belongs_to :buyer, optional: true, class_name: "User"
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  belongs_to :category
  enum prefecture:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
   }
   validates :saler_id,         presence: true
   validates :name,             presence: true
   validates :item_discription, presence: true
   validates :category_id,      presence: true
   validates :size,             presence: true
   validates :quolity,          presence: true
   validates :price,            presence: true, numericality: { only_integer: true,

                                                greater_than: 300, less_than: 9999999
                                                
                                                }
   validates :carriage_fee,     presence: true
   validates :prefecture,       presence: true
   validates :delivery,         presence: true
   validates :days,             presence: true
   validates :images,           associated: true

   validate :require_any_images
    def require_any_images
      errors.add("画像が登録されていません") if images.blank?
    end

    def self.search(search)
      return Item.all unless search
      Item.where('name LIKE ?', "%#{search}%")
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_parent, only: [:new, :create, :edit]
  before_action :set_item, only: [:edit, :update, :destroy, :show, :pay]
  def index
    @items = Item.all.order("created_at DESC").limit(15)
  end

  def show
    @saler_other_items = Item.where(saler_id: @item.saler.id) 
    @same_category_items = Item.where(category_id: @item.category.id)
  end

  def new
    @item = Item.new
    @item.images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end


  def search
    @items = Item.search(params[:keyword]).page(params[:page]).per(16)
  end

  def pay
    @item.update(buyer_id: current_user.id)
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    charge = Payjp::Charge.create(
    amount: @item.price,
    customer: current_user.card.customer_id,
    currency: 'jpy'
    )
    redirect_to done_purchase_index_path
    
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end

  end

   def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :edit
    end
   end


  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
  
  private

  def set_parent
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
  end

  def set_item
    @item = Item.find(params[:id])
  end
  
  def item_params
    params.require(:item).permit(:name, :item_discription, :category_id, :size, :brand_name, :quolity, :prefecture, :price, :carriage_fee, :delivery, :days, images_attributes: [:source, :_destroy, :id]).merge(saler_id: current_user.id)
  end
 
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.in-main__container__sell__data
  .in-main__container__sell
    .in-main__container__sell__head 商品情報を入力
    .in-main__container__sell__form
      .in-main__container__sell__form__box
        %h.in-main__container__sell__form__box--image 出品画像
        %span.in-main__container__sell__form__box--text 必須
        %p.in-main__container__sell__form__box--info 最大10枚までアップロードできます
        #image-box
          #previews
            - if @item.persisted?
              - @item.images.each_with_index do |image, i|
                = image_tag image.source.url, data: { index: i }, width: "100", height: '100'
          = form.fields_for :images do |image|
            .js-file_group{"data-index" => "#{image.index}"}
              = image.file_field :source, class: 'js-file'
              %br/
              %span.js-remove 削除
            - if @item.persisted?
              = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
          - if @item.persisted?
            .js-file_group{"data-index" => "#{@item.images.count}"}
              = file_field_tag :source, name: "item[images_attributes][#{@item.images.count}][source]", class: 'js-file'
              .js-remove 削除

      .in-main__container__sell__form__content1
        .in-main__container__sell__form__content1__group1
          .in-main__container__sell__form__content1__group1__label
            .in-main__container__sell__form__content1__group1__label__name
              商品名
            .in-main__container__sell__form__content1__group1__label__span
              必須
        .in-main__container__sell__form__content1__group2
          = form.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "in-main__container__sell__form__content1__group2__input"
        .in-main__container__sell__form__content1__group3
          .in-main__container__sell__form__content1__group3__label
            .in-main__container__sell__form__content1__group3__label__text
              商品の説明
            .in-main__container__sell__form__content1__group3__label__span
              必須
          .in-main__container__sell__form__content1__group3__textarea
            = form.text_area :item_discription, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "in-main__container__sell__form__content1__group3__textarea__form"

      .in-main__container__sell__form__content2
        .in-main__container__sell__form__content2__inner
          商品の詳細
          #categoryForm.in-main__container__sell__form__content2__inner__select
            .in-main__container__sell__form__content2__inner__select__top
              %h.in-main__container__sell__form__content2__inner__select__top__left
                商品の状態
                %span.in-main__container__sell__form__content2__inner__select__top__right
                  必須
            .in-main__container__sell__form__content2__inner__select__wrappe
              = icon 'fa', 'chevron-down', class: 'in-fa'
              = form.select :quolity, [["新品・未使用", "新品・未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]], {prompt: "--"}, {class: "button-in"}
            .in-main__container__sell__form__content2__inner__select__dwon
              %h.in-main__container__sell__form__content2__inner__select__dwon__left
                ブランド
                %span.in-main__container__sell__form__content2__inner__select__dwon__any
                  任意
            .in-main__container__sell__form__content2__inner__select__wrappe
              = form.text_field :brand_name, placeholder: "ブランド名", class: "button-in"
            .in-main__container__sell__form__content2__inner__select__dwon
              %h.in-main__container__sell__form__content2__inner__select__dwon__left
                サイズ
                %span.in-main__container__sell__form__content2__inner__select__top__right
                  必須
            .in-main__container__sell__form__content2__inner__select__wrappe
              = form.select :size, [["XS以下", "XS以下"], ["XS", "XS"], ["S", "S"], ["M", "M"], ["L", "L"], ["XL", "XL"], ["2XL", "2XL"]], {prompt: "--"}, {class: "button-in"}
            .in-main__container__sell__form__content2__inner__select__dwon
              %h.in-main__container__sell__form__content2__inner__select__dwon__left
                カテゴリー
                %span.in-main__container__sell__form__content2__inner__select__dwon__right
                  必須
            .in-main__container__sell__form__content2__inner__select__wrappe
              = icon 'fa', 'chevron-down', class: 'in-fa'
              %select.button-in#parent_category
                %option{:value => "--"} --
                - @category_parent_array.each do |c|
                  %option{:value => "#{c}"}= c

      .in-main__container__sell__form__content3 
        .in-main__container__sell__form__content3__label
          .in-main__container__sell__form__content3__label__inner
            配送について       
          %a.in-main__container__sell__form__content3__label__q{href: "/jp/help_center/article/68/", target: "_blank"} ?
        .in-main__container__sell__form__content3__select
          .in-main__container__sell__form__content3__select__top
            %h.in-main__container__sell__form__content3__select__top__left
              配送料の負担
              %span.in-main__container__sell__form__content3__select__top__right
                必須
          .in-main__container__sell__form__content3__select__wrappe
            = icon 'fa', 'chevron-down', class: 'in-fa'
            = form.select :carriage_fee, [["送料込み（出品者負担）", "送料込み（出品者負担）"], ["着払い（購入者負担）", "着払い（購入者負担）"]], {prompt: "--"}, {class: "button-in"}
          .in-main__container__sell__form__content3__select__top
            %h.in-main__container__sell__form__content3__select__top__left
              配送の方法
              %span.in-main__container__sell__form__content3__select__top__right
                必須
          .in-main__container__sell__form__content3__select__wrappe
            = icon 'fa', 'chevron-down', class: 'in-fa'
            = form.select :delivery, [["未定", "未定"], ["らくらくメルカリ便", "らくらくメルカリ便"], ["ゆうメール", "ゆうメール"], ["レターパック", "レターパック"], ["普通郵便", "普通郵便"], ["クロネコヤマト", "クロネコヤマト"]], {prompt: "--"}, {class: "button-in"}
          .in-main__container__sell__form__content3__select__top2
            %h.in-main__container__sell__form__content3__select__top2__left
              発送元の地域
              %span.in-main__container__sell__form__content3__select__top2__right
                必須
          .in-main__container__sell__form__content3__select__wrappe
            = icon 'fa', 'chevron-down', class: 'in-fa'
            = form.select :prefecture, Item.prefectures.keys, {}, {class: 'button-in'}
          .in-main__container__sell__form__content3__select__top3
            %h.in-main__container__sell__form__content3__select__top3__left
              発送までの日数
              %span.in-main__container__sell__form__content3__select__top3__right
                必須
          .in-main__container__sell__form__content3__select__wrappe
            = icon 'fa', 'chevron-down', class: 'in-fa'
            = form.select :days, [["1~2日で発送", "1~2日で発送"], ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"]], {prompt: "--"}, {class: "button-in"}

      .in-main__container__sell__form__content4    
        .in-main__container__sell__form__content4__label
          .in-main__container__sell__form__content4__label__inner
            販売価格(300~9,999,999)       
          %a.in-main__container__sell__form__content4__label__q{href: "/jp/help_center/article/68/", target: "_blank"} ?    
        .in-main__container__sell__form__content4__form
          .in-main__container__sell__form__content4__form__main
            .in-main__container__sell__form__content4__form__main__left
              .in-main__container__sell__form__content4__form__main__left__text
                価格
              .in-main__container__sell__form__content4__form__main__left__span
                必須
            .in-main__container__sell__form__content4__form__main__right
              .in-main__container__sell__form__content4__form__main__right__yen
                ¥
              = form.text_area :price, placeholder: "例）300", class: "in-main__container__sell__form__content4__form__main__right__input", id: "in-price"
          .in-main__container__sell__form__content4__form__com
            .in-main__container__sell__form__content4__form__com__left
              販売手数料(10%)
            #in-commition.in-main__container__sell__form__content4__form__com__right
              -
          .in-main__container__sell__form__content4__form__bold
            .in-main__container__sell__form__content4__form__bold__left
              販売利益
            #in-profit.in-main__container__sell__form__content4__form__bold__right
              _
            
      .in-main__container__sell__form__content5
        .in-main__container__sell__form__content5__text
          禁止されている出品、行為を必ずご確認ください。
        .in-main__container__sell__form__content5__text
          またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
        .in-main__container__sell__form__content5__text
          また、出品をもちまして加盟店規約に同意したことになります。
        - if @item.saler_id == nil
          = form.submit '登録する', class: "in-btn-red"
          %button.in-btn-gray{type: "back"}
            戻る
        - else
          - if @item.saler_id == current_user.id
            = form.submit '登録する', class: "in-btn-red"
            = link_to "商品を削除する", item_path(@item), method: :delete, data: { confirm: "本当に削除しますか?"}, class: "in-btn-red", id: "item-destroy"
          - else
            %h.in-btn-red
              この商品の編集はできません
          %button.in-btn-gray{type: "back"}
            戻る

app/views/items/edit.html.haml
= render 'shared/header2'

.in-main
  .in-main__container
    = form_with model: @item, url: "/items/#{@item.id}", class: "in-main__container__sell", local: true do |form|
      = render partial: "form", locals: { form: form }

= render 'shared/footer2'

app/views/items/index.html.haml
.wrapper
  = render 'shared/header1'
  .ii-top
    .ii-menu
      .ii-info 
        = image_tag 'street_background.jpg', class: "ii-info__image"
      .ii-tag
        %h1.ii-tag--title 人気のカテゴリー
        .ii-tag__categorys
          %ul.ii-tag__categorys__list
            %li.ii-tag__categorys__list__name レデイース
            %li.ii-tag__categorys__list__name メンズ
            %li.ii-tag__categorys__list__name ベビー
      .ii-contents
        .ii-contents-nav
          .ii-contents-nav__name
            %h1.ii-contents-nav__name--title 商品一覧
            = link_to "もっとみる >", root_path, class: "ii-contents-nav__name--link"
          .ii-contents-nav__items
            .ii-contents-nav__items__list
              %ul.ii-contents-nav__items__list__items
                - @items.each do |item|
                  = link_to "items/#{item.id}",class: "ii-contents-nav__items__list__items__item", method: :get do
                    %li
                      = image_tag item.images[0].source.url,width: "100%",height: "170px"
                      .ii-contents-nav__items__list__items__item__price
                        .ii-contents-nav__items__list__items__item__price__box
                          ¥ 
                          = item.price.to_s(:delimited)
                      .ii-name
                        = item.name.truncate(20)


  = render 'shared/camera'
  = render 'shared/footer1'

app/views/items/new.html.haml
= render 'shared/header2'

.in-main
  .in-main__container
    = form_with model: @item, url: '/items/create', class: "in-main__container__sell", local: true do |form|
      = render partial: "form", locals: { form: form }

= render 'shared/footer2'

app/views/items/search.html.haml
= render 'shared/header1'
%main.main
  .search-sidebar
  .search-content
    %section.ise-item
      - @items.each do |item|
        = link_to item_path(item.id), class: "ise-link" do
          .ise-item-box
            %figere.ise-item-box__image
              = image_tag item.images[0].source.url,width: "100%",height: "170px"
            .ise-item-box__text
              %h.ise-item-box__text--name
                = item.name
              .ise-item-box__text--price 
                ¥
                = item.price
    = paginate(@items)

 

app/views/items/show.html.haml
.wrapper

  = render 'shared/header1'



  .is-item-box
    %h1.is-item-name 
      = @item.name
    .is-item-box__main-content

      .is__photo
        .is__photo__place
          .is__photo__place__sample
            .is__photo__place__sample__stage
              - @item.images.each do |image|
                .is__photo__place__sample__stage__in
                  .is__photo__place__sample__stage__in__img
                    = image_tag "#{image.source}", size: "300x300"
          .is__photo__place__disabled
          #is__photo__place__dots
            - @item.images.each do |image|
              = image_tag "#{image.source}", size: "60x60"

      %table.is__table
        %tbody
          %tr.is__table-record
            %th.is__table-header 出品者
            %td.is__table-data
              .is__table-data__username 
                = @item.saler.nickname
              .is__table__user-rating
                = icon 'fas', 'laugh', class: 'is__table__user-rating__laugh'
              .is__table__user-rating
                = icon 'fas', 'meh', class: 'is__table__user-rating__meh'
              .is__table__user-rating
                = icon 'fas', 'frown', class: 'is__table__user-rating__frown'
          %tr.is__table-record
            %th.is__table-header カテゴリー
            %td.is__table-data
              = link_to root_path, class: 'is__table-data__category' do
                = @item.category.parent.parent.name
              = link_to root_path, class: 'is__table-data__category' do
                = icon 'fas', 'angle-right'
                = @item.category.parent.name
              = link_to root_path, class: 'is__table-data__category' do
                = icon 'fas', 'angle-right'
                = @item.category.name
          %tr.is__table-record
            %th.is__table-header ブランド
            %td.is__table-data 
              = @item.brand_name
          %tr.is__table-record
            %th.is__table-header 商品のサイズ
            %td.is__table-data 
              = @item.size
          %tr.is__table-record
            %th.is__table-header 商品の状態
            %td.is__table-data 
              = @item.quolity
          %tr.is__table-record
            %th.is__table-header 配送料の負担
            %td.is__table-data 
              = @item.carriage_fee
          %tr.is__table-record
            %th.is__table-header 配送の方法
            %td.is__table-data 
              = @item.delivery
          %tr.is__table-record
            %th.is__table-header 配送元地域
            %td.is__table-data 
              = link_to "#{@item.prefecture}", root_path, class: 'is__table-data__enum'
          %tr.is__table-record
            %th.is__table-header 発送日の目安
            %td.is__table-data 
              = @item.days

    .is-item-box__price-box
      .is-item-price-large 
        ¥
        = @item.price
      .is-item-tax 
        （税込）
      .is-item-stopfee 
        = @item.carriage_fee
    - if user_signed_in?
      - if @item.saler_id == current_user.id
        = link_to edit_item_path(@item), class: 'is-item-buy-btn' do
          商品情報の編集に進む
      - else 
        - if @item.buyer_id == nil 
          = link_to purchase_index_path(item_id: @item.id), class: 'is-item-buy-btn' do
            購入画面に進む
        - else
          = link_to root_path, class: 'is-item-buy-btn' do
            この商品は購入されています
    - else
      = link_to new_user_registration_path, class: 'is-item-buy-btn' do
        購入画面に進む
      


    %p.is-item-box__error-message この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
    
    .is-item-box__description
      .is-item-box__description__inner 
        = simple_format @item.item_discription
      

    .is-item-box__button
      .is-item-box__button__left
        %button.is-button.is-button__like
          = icon 'far', 'heart', class: 'is-icon'
          %span.is__writing いいね！
          %span.is__num 
        = link_to root_path, class: 'is-button is-button__report' do
          = icon 'far', 'flag', class: 'is-icon'
          %span.is__writing 不適切な商品の報告
      .is-item-box__button__right
        = link_to root_path, class: 'is-safety' do
          = icon 'fas', 'lock', class: 'is-icon'
          %span.is__writing あんしん・あんぜんへの取り組み



  .is-message-box
    .is-message-box__container
      .is-message-box__container__content
        %form.is-message-form
          %p.is-message-form__note 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %textarea.is-message-form__note__area
        %button.is-comment-btn
          %span.is-btn__comment コメントする

  %ul.is-next-item
    %li.is-next-item__left
      = link_to root_path, class: 'is-randomitem' do
        = icon 'fas', 'angle-left', class: 'is-icon-left'
        前の商品
    %li.is-next-item__right
      = link_to root_path, class: 'is-randomitem' do
        次の商品
        = icon 'fas', 'angle-right', class: 'is-icon-right'



  .is-media-links
    %ul.is-media-links__case
      %li.is-media-links__case__app
        =link_to "https://www.facebook.com/", class: "is-app-btn" do
          = icon 'fab', 'facebook-square', class: 'is-facebook'
      %li.is-media-links__case__app
        =link_to "https://twitter.com/", class: "is-app-btn" do
          = icon'fab', 'twitter', class: 'is-twitter'
      %li.is-media-links__case__app__last
        =link_to "https://www.instagram.com/", class: "is-app-btn" do
          = icon 'fab', 'instagram', class: 'is-instagram'



  .is-user-items
    %section.is-user-items__others
      %h2.is-user-items__others__name 
        = link_to "ユーザーさんのその他の出品", root_path
      .is-user-items__others__exhibit
        - @saler_other_items.each do |item| 
          - if item.id != @item.id  # 現在表示している商品は関連に表示しない
            %section.is-user-items__others__exhibit__boxes
              = link_to item_path(item.id), class: 'is-user-items__others__exhibit__boxes__link' do
                %figure.is-user-items__others__exhibit__boxes__photo
                  - thumbnail = Image.find_by(item_id: item.id) # サムネイルとして商品の先頭に登録されている画像のみを取り出す
                  = image_tag "#{thumbnail.source}", class: 'is-user-items__others__exhibit__boxes__photo__img'
                .is-user-items__others__exhibit__boxes__body
                  %h3.is-user-items__others__exhibit__boxes__body__name 
                    = item.name
                  .is-user-items__others__exhibit__boxes__body__price 
                  ¥
                  = item.price
  .is-user-items
    %section.is-user-items__others
      %h2.is-user-items__others__name 
        = link_to "同一ジャンルのその他の商品", root_path
      .is-user-items__others__exhibit
        - @same_category_items.each do |item| 
          - if item.id != @item.id  # 現在表示している商品は関連に表示しない
            %section.is-user-items__others__exhibit__boxes
              = link_to item_path(item.id), class: 'is-user-items__others__exhibit__boxes__link' do
                %figure.is-user-items__others__exhibit__boxes__photo
                  - thumbnail = Image.find_by(item_id: item.id) # サムネイルとして商品の先頭に登録されている画像のみを取り出す
                  = image_tag "#{thumbnail.source}", class: 'is-user-items__others__exhibit__boxes__photo__img'
                .is-user-items__others__exhibit__boxes__body
                  %h3.is-user-items__others__exhibit__boxes__body__name 
                    = item.name
                  .is-user-items__others__exhibit__boxes__body__price 
                  ¥
                  = item.price


  = render 'shared/footer1'